# Two-stage Decision Tree Visualization
# Decision Node 1
print("Decision Node 1: 40")
print("|")
print("|--> Chance Node 1: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
print("|")
print("|--> Chance Node 2: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
print("|")
print("|--> Chance Node 3: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")

# Decision Node 2
print("Decision Node 2: 50")
print("|")
print("|--> Chance Node 1: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
print("|")
print("|--> Chance Node 2: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
print("|")
print("|--> Chance Node 3: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")

# DECISION 3
print("Decision Node 3: 60")
print("|")
print("|--> Chance Node 1: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
print("|")
print("|--> Chance Node 2: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
print("|")
print("|--> Chance Node 3: 44, 34.2, 24.4")
print("|    |")
print("|    |--> Outcome 1: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 2: Cost = C_nf + C_penalty")
print("|    |")
print("|    |--> Outcome 3: Cost = C_nf + C_penalty")
